#!/usr/bin/env python3
# coding: utf-8

import importlib
import sys
import os


BUSRUN_COMMANDS_APP_NAME = "バスルン コマンドラインツール"
BUSRUN_COMMANDS_VERSION = "25.08-1"

BUSRUN_DATA_DIR = "../data"


def mes (log_text, is_error=False, is_heading=False):
    if is_error:
        print("\x1b[31m\x1b[1m【エラー】\x1b[22m" + str(log_text) + "\x1b[0m")
    elif is_heading:
        print("\n\x1b[94m_/_/_/_/\x1b[0m " + str(log_text) + " \x1b[94m_/_/_/_/\x1b[0m\n")
    else:
        print(str(log_text))


args = []
options = set()
arg_count = 0
for arg_index in range(1, len(sys.argv)):
    if sys.argv[arg_index].startswith("-"):
        options.add(sys.argv[arg_index])
    else:
        args.append(sys.argv[arg_index])
        arg_count += 1

if "-s" not in options:
    print(BUSRUN_COMMANDS_APP_NAME + " \x1b[90mv" + BUSRUN_COMMANDS_VERSION + "\x1b[0m")

os.chdir(os.path.dirname(os.path.abspath(__file__)))
data_dir = (os.path.abspath(BUSRUN_DATA_DIR))

if arg_count >= 1:
    match args[0]:
        case "get-gtfs-realtime":
            if arg_count <= 2:
                get_gtfs_realtime = importlib.import_module("modules.get_gtfs_realtime")
                if arg_count == 1:
                    get_gtfs_realtime.get_gtfs_realtime(mes, options=options)
                else:
                    get_gtfs_realtime.get_gtfs_realtime(mes, args[1], options=options)
            else:
                print("\x1b[31m引数の数が異常です\x1b[0m")
        case "conv-diagram-info":
            if arg_count == 3:
                conv_diagram_info = importlib.import_module("modules.conv_diagram_info")
                conv_diagram_info.conv_diagram_info(mes, data_dir + "/" + os.path.basename(args[1]), os.path.basename(args[2]))
            else:
                print("\x1b[31m引数の数が異常です\x1b[0m")
        case "init-db":
            if arg_count == 2:
                init_db = importlib.import_module("modules.init_db")
                init_db.init_db(mes, data_dir + "/" + os.path.basename(args[1]))
            else:
                print("\x1b[31m引数の数が異常です\x1b[0m")
        case _:
            print("\x1b[31mコマンド \x1b[1m" + args[0] + "\x1b[22m は存在しません\x1b[0m")
